GTR/forum/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include

from . import views

urlpatterns = [

    # URL pattern for the UserUpdateView
    url(regex=r'^$', view=views.LinkListView.as_view(), name='forum'),
    url(regex=r'^create/$', view=views.LinkCreateView.as_view(), name='create'),
    url(regex=r'^(?P<pk>\d+)/$', view=views.LinkDetailView.as_view(), name='link_detail'),
    url(regex=r'^update/(?P<pk>\d+)/$', view=views.LinkUpdateView.as_view(), name='link_update'),
    url(regex=r'^delete/(?P<pk>\d+)/$', view=views.LinkDeleteView.as_view(), name='link_delete'),
    url(regex=r'^vote/$', view=views.VoteFormView.as_view(), name='vote'),
    url(regex=r'^agree/$', view=views.agree, name='agree'),
    url(regex=r'^disagree/$', view=views.disagree, name='disagree'),
    url(regex=r'^search/$', view=views.SearchListView.as_view(), name='search'),
    #url(r'^comments/', include('django_comments.urls'), name='comments'),
]

GTR/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(regex=r'^$', view=views.UserListView.as_view(), name='list'),

    # URL pattern for the UserRedirectView
    url(regex=r'^~redirect/$', view=views.UserRedirectView.as_view(), name='redirect'),

    # URL pattern for the UserDetailView
    url(regex=r'^(?P<username>[\w.@+-]+)/$', view=views.UserDetailView.as_view(), name='detail'),

    # URL pattern for the UserUpdateView
    url(regex=r'^~update/$', view=views.UserUpdateView.as_view(), name='update'),

]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

# generate 

from django.contrib.sitemaps import GenericSitemap
from GTR.forum.models import Link
from django.contrib.sitemaps import Sitemap

class MainSitemap( Sitemap ):
 
  def items(self):
    return [self]

  location = "/"
  changefreq = "monthly"
  priority = "1"

Link_dict = {
    'queryset': Link.objects.all(),
    'date_field': 'submitted_on',
}


sitemaps = {
    'link': GenericSitemap(Link_dict, priority=0.8),
    'main_page' : MainSitemap,
}

urlpatterns = [
    url(r'^home/$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin
    url(r'^admin_musashi/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("GTR.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here

    url(r'^',  include("GTR.forum.urls", namespace="forum")),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

GTR/forum/models.py
from django.db import models

#from django.contrib.auth.models import User
from GTR.users.models import User
from django.db.models import Count
from django.core.urlresolvers import reverse

class LinkVoteCountManager(models.Manager):
    def get_queryset(self):
        return super(LinkVoteCountManager, self).get_queryset().annotate(
            votes=Count('vote')).order_by("-submitted_on","-votes")

class Link(models.Model):
    title = models.CharField("", max_length=100)
    submitter = models.ForeignKey(User)
    submitted_on = models.DateTimeField(auto_now_add=True)
    rank_score = models.FloatField(default=0.0)
    url = models.URLField("URL", max_length=250, blank=True)
    self_description = models.CharField("", blank=True, max_length=75)
    description = models.TextField("")
    with_votes = LinkVoteCountManager()
    objects = models.Manager() #default manager
    agree = models.IntegerField(default=0)
    disagree = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("forum:link_detail", kwargs={"pk": str(self.id)})

class Vote(models.Model):
    voter = models.ForeignKey(User)
    link = models.ForeignKey(Link)

    def __unicode__(self):
        return "%s upvoted %s" % (self.voter.username, self.link.title)

GTR/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
#from django.db import models
# from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    def __unicode__(self):
        return self.username

GTR/forum/forms.py
from django import forms
from .models import Link, Vote


class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        exclude = ("submitter", "rank_score", "agree", "disagree", "url")
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title', 'class':'form-control link-form-control', 'required':''}),
            'self_description': forms.TextInput(attrs={'class':'form-control link-form-control', 'placeholder':'Self Description (e.g. Mid 20s/Software Engineer/$80-90k Salary/Bay Area)'}),
            'description': forms.Textarea(attrs={'class':'form-control link-form-control', 'placeholder': 'Tell us your story', 'required':''})
        }


class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = '__all__'

GTR/users/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

GTR/forum/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import ListView
from .models import Link, Vote
from django.views.generic.edit import CreateView
from .forms import LinkForm, VoteForm
from braces.views import LoginRequiredMixin
from django.views.generic import DetailView
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.views.generic.edit import FormView
import json
from django.http import HttpResponse
import operator
from functools import reduce
from django.db.models import Q



class SearchListView(ListView):
    model = Link
    queryset = Link.with_votes.all()
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(SearchListView, self).get_context_data(**kwargs)
        context["no_jumbotron"] = True
        context["search_results"] = True
        return context

    def get_queryset(self):
        result = super(SearchListView, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(title__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(description__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(self_description__icontains=q) for q in query_list))
            )
        return result

class LinkListView(ListView):
    model = Link
    queryset = Link.with_votes.all()
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(LinkListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            links_in_page = [link.id for link in context["object_list"]]
            voted = voted.filter(link_id__in=links_in_page)
            voted = voted.values_list('link_id', flat=True)
            context["voted"] = voted

        context["no_jumbotron"] = True

        has_commented =[] # empty list
        for link in context["object_list"]:
            if (True == self.request.session.get('has_commented_' + str(link.id))): # pk is the object id
                has_commented.append(link.id)
        
        context["has_commented"] = has_commented

        return context

class LinkCreateView(LoginRequiredMixin, CreateView):
    model = Link
    form_class = LinkForm
    #template_name = "link_form.html"

    def form_valid(self, form):
        f = form.save(commit=False)
        f.rank_score = 0.0
        f.submitter = self.request.user
        f.save()

        return super(CreateView, self).form_valid(form)

class LinkDetailView(DetailView):

    model = Link
    def get_context_data(self, **kwargs):
        context = super(LinkDetailView, self).get_context_data(**kwargs)
        has_commented = self.request.session.get('has_commented_' + self.kwargs['pk']) # pk is the object id
        #print (self.kwargs['pk'])
        #print (has_commented) # if we don't setup the has_comment, the default value is None
        context["has_commented"] = has_commented
        context["no_jumbotron"] = True

        return context
        
def agree(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['obj_id']

    agree_count = 0

    if cat_id:
        cat = Link.objects.get(id=int(cat_id))
    if cat:
        if request.session.get('has_commented_' + cat_id, False):
            agree_count = cat.agree
        else:
            request.session['has_commented_' + cat_id] = True
            agree_count = cat.agree + 1
            cat.agree =  agree_count
            cat.save()
    return HttpResponse(agree_count)

def disagree(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['obj_id']

    disagree_count = 0

    if cat_id:
        cat = Link.objects.get(id=int(cat_id))
    if cat:
        if request.session.get('has_commented_' + cat_id, False):
            disagree_count = cat.disagree
        else:
            request.session['has_commented_' + cat_id] = True
            disagree_count = cat.disagree + 1
            cat.disagree =  disagree_count
            cat.save()
    return HttpResponse(disagree_count)

class LinkUpdateView(LoginRequiredMixin, UpdateView):
    model = Link
    form_class = LinkForm

class LinkDeleteView(LoginRequiredMixin, DeleteView):
    model = Link
    success_url = reverse_lazy("forum:forum")

class JSONFormMixin(object):
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict), content_type='application/json')
        response.status = 200 if valid_form else 500
        return response

class VoteFormBaseView(LoginRequiredMixin, FormView):
    form_class = VoteForm

    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict))
        response.status = 200 if valid_form else 500
        return response

    def form_valid(self, form):
        link = get_object_or_404(Link, pk=form.data["link"])
        user = self.request.user
        prev_votes = Vote.objects.filter(voter=user, link=link)
        has_voted = (len(prev_votes) > 0)

        ret = {"success": 1}
        if not has_voted:
            # add vote
            v = Vote.objects.create(voter=user, link=link)
            ret["voteobj"] = v.id
        else:
            # delete vote
            prev_votes[0].delete()
            ret["unvoted"] = 1
        return self.create_response(ret, True)

    def form_invalid(self, form):
        ret = {"success": 0, "form_errors": form.errors }
        return self.create_response(ret, False)

class VoteFormView(JSONFormMixin, VoteFormBaseView):
    pass

GTR/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .forms import UserForm
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

GTR/templates/forum/link_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<p>Are you sure you want to delete "{{ object.title }}"?</p>

<form method="post" action="{% url 'forum:link_delete' pk=object.pk %}">
  {% csrf_token %}
  <a href="{% url 'forum:link_detail' pk=object.pk %}">Go back</a> 
  <p><input type="submit" value="Confirm deletion" /></p>
</form> 

{% endblock %}

GTR/templates/forum/link_detail.html
{% extends "base.html" %}
{% load time_filters %}
{% load static %}
{% load comments %}w

{% block content %}

<style>
  h4 { display:inline; }

  #id_honeypot {
    display: none;
  }

  .btn {
        padding: 0px;
        padding-left: 5px;
        padding-right: 5px;
  }

  .comment_header{
    background-color: #eee;
    -moz-border-radius: 0px;
    -webkit-border-radius: 4px 4px 0px 0px;
    border-radius: 4px 4px 0px 0px; 
  }

  .comment_form{
    position: relative;
    padding:30px !important;
    padding-top:0 !important;
    margin-top:0 !important;
    background-color: #eee;
    text-align:left;
    margin-bottom: 0 !important;
    -moz-border-radius: 0px;
    -webkit-border-radius: 0px 0px 4px 4px;
    border-radius: 0px 0px 4px 4px; 
  }
</style>



<div class="panel panel-info">
  <div class="panel-body">
    <h4 class="text-left"><a href="{{ object.link }}">{{ object.title }}</a></h4>
    {% if object.self_description%}
    <small class="mic-info"><strong><i> - {{ object.self_description }}</i></strong></small>
    {% endif %}
    <small class="mic-info" style="float:right;">{{link.submitted_on|timesince|upto:','}} ago by <strong style="color:green">{{link.submitter}}</strong></small>
    <br/><br/>
    <div>
    {{ object.description }}
    </div>
    {% if object.submitter == user or user.username == 'admin' %}
      <br/>
      <a href="{% url 'forum:link_update' pk=object.pk %}">Edit</a> | 
      <a href="{% url 'forum:link_delete' pk=object.pk %}">Delete</a>
    {% endif %}
  </div>
  <div class="panel-footer">

{% if has_commented != True %}

    <button data-catid="{{ object.pk }}" id="agree_button_{{ object.pk }}" class="btn btn-primary agree" type="button">
    <span class="glyphicon glyphicon-hand-right"></span>
    Quit!
    </button>

    <span class="label label-success"><strong id="agree_count_{{ object.pk }}">{{ object.agree }}</strong></span>

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <button data-catid="{{ object.pk }}" id="disagree_button_{{ object.pk }}" class="btn btn-primary disagree" type="button">
    <span class="glyphicon glyphicon-hand-down"></span>
    Stay!
    </button>
    
    <span class="label label-danger"><strong id="disagree_count_{{ object.pk }}">{{ object.disagree }}</strong></span>

{% else %}
    <button disabled data-catid="{{ object.pk }}" id="agree_button_{{ object.pk }}" class="btn btn-primary agree" type="button">
    <span class="glyphicon glyphicon-hand-right"></span>
    Quit!
    </button>

    <span class="label label-success"><strong id="agree_count_{{ object.pk }}">{{ object.agree }}</strong></span>

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <button disabled data-catid="{{ object.pk }}" id="disagree_button_{{ object.pk }}" class="btn btn-primary disagree" type="button">
    <span class="glyphicon glyphicon-hand-down"></span>
    Stay!
    </button>
    
    <span class="label label-danger"><strong id="disagree_count_{{ object.pk }}">{{ object.disagree }}</strong></span>
{% endif %}
  </div>
</div>

<p>

</p>

<li class="list-group-item comment_header">
  <span class="glyphicon glyphicon-comment"></span>
  <h4> Comments </h4>
  <span class="label label-info">{% get_comment_count for link as comment_count %}{{ comment_count }}</span>
</li>
<!--{% render_comment_list for object %}-->
{% get_comment_list for object as comment_list %}
{% for comment in comment_list %}
<li class="list-group-item">
        <b>{{ comment.user_name }}</b>&nbsp;&nbsp;<small class="mic-info">{{ comment.submit_date|timesince|upto:',' }} ago</small></br>
        {{ comment.comment }} </br>
</li>
{% endfor %}

<div class="comment_form">
    <div class="row">
        <div class="widget-area no-padding blank">
            <div class="status-upload">
                <span class="glyphicon glyphicon-share-alt"></span>
                <h4> Reply </h4>
                {% get_comment_form for object as form %}
                <form action="{% comment_form_target %}" method="POST" class="link-form">
                    {% csrf_token %}
                    {{ form.honeypot }}
                    {{ form.content_type }}
                    {{ form.object_pk }}
                    {{ form.timestamp }}
                    {{ form.security_hash }}
                    {% if user.is_authenticated %}
                        <input type="hidden" name="name" value="{{ user }}" />
                    {% else %}
                        <input type="text" name="name" class="form-control link-form-control" placeholder="Your Nickname" style="border: 1px solid #cccccc;" required/>
                    {% endif %}
                    <textarea name="comment" maxlength=3000 class="link-form link-form-control" placeholder="Your comments" style="border: 1px solid #cccccc;" required/></textarea>
                    <input type="hidden" name="email" value="{{ user.email|default:'d@ummy.com' }}" />
                    <!--<input type="hidden" name="url" value="" />-->
                    <input type="hidden" name="next" value="{% url 'forum:link_detail' pk=object.id %}" />
                    <button type="submit" class="btn main-btn pull-left" value="Add comment" id="id_submit"><i class="fa fa-share"></i>Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
</br></br>

{% endblock %}

GTR/templates/forum/link_form.html
{% extends "base.html" %}

{% block content %}
<h2>Post</h2>
<div class="row">
    <form method="post" action="" class="link-form">
        <div class="col-md-12">
            <div class="form-group">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn main-btn pull-right">Submit</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

GTR/templates/forum/link_list.html
{% extends "base.html" %}
{% load time_filters %}
{% load comments %}

{% block content %}

<style>
    h3 { color: #ffffff;}
    h4 { display:inline; }
    h5 { color: #ffffff;}
    .btn {
        padding: 0px;
        padding-left: 5px;
        padding-right: 5px;
    }
</style>


{% if search_results %}
    {% if object_list.count == 0 %}
        <h3> No results found.</h3></br>
    {% else %}
        <h3> Search Results: {{ object_list.count }} </h3></br>
    {% endif %}
{% else %}

<div class="panel panel-info" style="border-color: #112e43;background-color: #112e43;">
  <div class="panel-body">
      <h3>Thinking of quitting? Tell us your story. <span class="hidden-xs">(╯°□°)╯︵ ┻━┻ </span></h3>
      <span class="hidden-lg hidden-md hidden-sm"><h3>(╯°□°)╯︵ ┻━┻ </h3></span>
      <h5>Maybe your job's not that bad afterall.</h5>
  </div>
</div>

{% endif %}

{% for link in object_list %}

<div class="panel panel-info">
  <div class="panel-body">
    <h4><a href="{% url 'forum:link_detail' pk=link.pk %}">{{ link.title }}</a></h4>
    {% if link.self_description%}
    <small class="mic-info"><strong><i> - {{ link.self_description }}</i></strong></small>
    {% endif %}
    <small class="mic-info" style="float:right;">{{link.submitted_on|timesince|upto:','}} ago by <strong style="color:green">{{link.submitter}}</strong></small>
    <br/><br/>
    <article>
    {{ link.description }}
    </article>
  </div>
  <div class="panel-footer">

    <button {% if link.pk in has_commented %} disabled {% endif %} data-catid="{{ link.pk }}" id="agree_button_{{ link.pk }}" class="btn btn-primary agree" type="button">
    <span class="glyphicon glyphicon-hand-right"></span>
    Quit!
    </button>

    <span class="label label-success"><strong id="agree_count_{{ link.pk }}">{{ link.agree }}</strong></span>

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <button {% if link.pk in has_commented %} disabled {% endif %} data-catid="{{ link.pk }}" id="disagree_button_{{ link.pk }}" class="btn btn-primary disagree" type="button">
    <span class="glyphicon glyphicon-hand-down"></span>
    Stay!
    </button>
    
    <span class="label label-danger"><strong id="disagree_count_{{ link.pk }}">{{ link.disagree }}</strong></span>
    
    <a href="{% url 'forum:link_detail' pk=link.pk %}" style="float:right;">
        <span class="glyphicon glyphicon-comment"></span>
        <span class="label label-info">{% get_comment_count for link as comment_count %}{{ comment_count }}</span>
    </a>
  </div>
</div>

<!--
<form method="post" action="{% url 'forum:vote' %}" class="vote_form">
    <li id = "id_vote"> [{{ link.votes }}] 
    	{% csrf_token %}
    	<input type="hidden" id="id_link" name="link" class="hidden_id" value="{{ link.pk }}" />
    	<input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
    	{% if not user.is_authenticated %}
	    	<button disabled title="Please login to vote">+</button>
	    {% elif link.pk not in voted %}
	    	<button>+</button>
	    {% else %}
	    	<button>-</button>
	    {% endif %}

    	<a href="{% url 'forum:link_detail' pk=link.pk %}">
    		<b>{{ link.title }}</b>
    		{% get_comment_count for link as comment_count %}
    		{{ comment_count }} comment{{ comment_count|pluralize }}
    	</a>
    </li>
</form>
-->

{% endfor %}

{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li><a href="?page={{page_obj.previous_page_number}}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><a href="#">&laquo;</a></li>
    {% endif %}
    {% if page_obj.number|add:"-2" in paginator.page_range %}
    <li><a href="?page={{ page_obj.number|add:"-2"}}">{{page_obj.number|add:"-2"}}</a></li>
    {% endif %}
    {% if page_obj.number|add:"-1" in paginator.page_range %}
    <li><a href="?page={{ page_obj.number|add:"-1"}}">{{page_obj.number|add:"-1"}}</a></li>
    {% endif %}
    <li class="active"><a href="?page={{ page_obj.number}}">{{page_obj.number}}</a></li>
    {% if page_obj.number|add:"1" in paginator.page_range %}
    <li><a href="?page={{ page_obj.number|add:"1"}}">{{page_obj.number|add:"1"}}</a></li>
    {% endif %}
    {% if page_obj.number|add:"2" in paginator.page_range %}
    <li><a href="?page={{ page_obj.number|add:"2"}}">{{page_obj.number|add:"2"}}</a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><a href="#">&raquo;</a></li>
    {% endif %}
</ul>
{% endif %}

{% endblock %}