GTR/forum/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include

from . import views

urlpatterns = [

    # URL pattern for the UserUpdateView
    url(regex=r'^$', view=views.LinkListView.as_view(), name='forum'),
    url(regex=r'^create/$', view=views.LinkCreateView.as_view(), name='create'),
    url(regex=r'^(?P<pk>\d+)/$', view=views.LinkDetailView.as_view(), name='link_detail'),
    url(regex=r'^update/(?P<pk>\d+)/$', view=views.LinkUpdateView.as_view(), name='link_update'),
    url(regex=r'^delete/(?P<pk>\d+)/$', view=views.LinkDeleteView.as_view(), name='link_delete'),
    url(regex=r'^vote/$', view=views.VoteFormView.as_view(), name='vote'),
    url(regex=r'^agree/$', view=views.agree, name='agree'),
    url(regex=r'^disagree/$', view=views.disagree, name='disagree'),
    url(regex=r'^search/$', view=views.SearchListView.as_view(), name='search'),
    #url(r'^comments/', include('django_comments.urls'), name='comments'),
]

GTR/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(regex=r'^$', view=views.UserListView.as_view(), name='list'),

    # URL pattern for the UserRedirectView
    url(regex=r'^~redirect/$', view=views.UserRedirectView.as_view(), name='redirect'),

    # URL pattern for the UserDetailView
    url(regex=r'^(?P<username>[\w.@+-]+)/$', view=views.UserDetailView.as_view(), name='detail'),

    # URL pattern for the UserUpdateView
    url(regex=r'^~update/$', view=views.UserUpdateView.as_view(), name='update'),

]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

# generate 

from django.contrib.sitemaps import GenericSitemap
from GTR.forum.models import Link
from django.contrib.sitemaps import Sitemap

class MainSitemap( Sitemap ):
 
  def items(self):
    return [self]

  location = "/"
  changefreq = "monthly"
  priority = "1"

Link_dict = {
    'queryset': Link.objects.all(),
    'date_field': 'submitted_on',
}


sitemaps = {
    'link': GenericSitemap(Link_dict, priority=0.8),
    'main_page' : MainSitemap,
}

urlpatterns = [
    url(r'^home/$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin
    url(r'^admin_musashi/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("GTR.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here

    url(r'^',  include("GTR.forum.urls", namespace="forum")),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

GTR/forum/models.py
from django.db import models

#from django.contrib.auth.models import User
from GTR.users.models import User
from django.db.models import Count
from django.core.urlresolvers import reverse

class LinkVoteCountManager(models.Manager):
    def get_queryset(self):
        return super(LinkVoteCountManager, self).get_queryset().annotate(
            votes=Count('vote')).order_by("-submitted_on","-votes")

class Link(models.Model):
    title = models.CharField("", max_length=100)
    submitter = models.ForeignKey(User)
    submitted_on = models.DateTimeField(auto_now_add=True)
    rank_score = models.FloatField(default=0.0)
    url = models.URLField("URL", max_length=250, blank=True)
    self_description = models.CharField("", blank=True, max_length=75)
    description = models.TextField("")
    with_votes = LinkVoteCountManager()
    objects = models.Manager() #default manager
    agree = models.IntegerField(default=0)
    disagree = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("forum:link_detail", kwargs={"pk": str(self.id)})

class Vote(models.Model):
    voter = models.ForeignKey(User)
    link = models.ForeignKey(Link)

    def __unicode__(self):
        return "%s upvoted %s" % (self.voter.username, self.link.title)

GTR/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
#from django.db import models
# from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    def __unicode__(self):
        return self.username

GTR/forum/forms.py
from django import forms
from .models import Link, Vote


class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        exclude = ("submitter", "rank_score", "agree", "disagree", "url")
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title', 'class':'form-control link-form-control', 'required':''}),
            'self_description': forms.TextInput(attrs={'class':'form-control link-form-control', 'placeholder':'Self Description (e.g. Mid 20s/Software Engineer/$80-90k Salary/Bay Area)'}),
            'description': forms.Textarea(attrs={'class':'form-control link-form-control', 'placeholder': 'Tell us your story', 'required':''})
        }


class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = '__all__'

GTR/users/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

GTR/forum/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import ListView
from .models import Link, Vote
from django.views.generic.edit import CreateView
from .forms import LinkForm, VoteForm
from braces.views import LoginRequiredMixin
from django.views.generic import DetailView
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.views.generic.edit import FormView
import json
from django.http import HttpResponse
import operator
from functools import reduce
from django.db.models import Q



class SearchListView(ListView):
    model = Link
    queryset = Link.with_votes.all()
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(SearchListView, self).get_context_data(**kwargs)
        context["no_jumbotron"] = True
        context["search_results"] = True
        return context

    def get_queryset(self):
        result = super(SearchListView, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(title__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(description__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(self_description__icontains=q) for q in query_list))
            )
        return result

class LinkListView(ListView):
    model = Link
    queryset = Link.with_votes.all()
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(LinkListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            links_in_page = [link.id for link in context["object_list"]]
            voted = voted.filter(link_id__in=links_in_page)
            voted = voted.values_list('link_id', flat=True)
            context["voted"] = voted

        context["no_jumbotron"] = True

        has_commented =[] # empty list
        for link in context["object_list"]:
            if (True == self.request.session.get('has_commented_' + str(link.id))): # pk is the object id
                has_commented.append(link.id)
        
        context["has_commented"] = has_commented

        return context

class LinkCreateView(LoginRequiredMixin, CreateView):
    model = Link
    form_class = LinkForm
    #template_name = "link_form.html"

    def form_valid(self, form):
        f = form.save(commit=False)
        f.rank_score = 0.0
        f.submitter = self.request.user
        f.save()

        return super(CreateView, self).form_valid(form)

class LinkDetailView(DetailView):

    model = Link
    def get_context_data(self, **kwargs):
        context = super(LinkDetailView, self).get_context_data(**kwargs)
        has_commented = self.request.session.get('has_commented_' + self.kwargs['pk']) # pk is the object id
        #print (self.kwargs['pk'])
        #print (has_commented) # if we don't setup the has_comment, the default value is None
        context["has_commented"] = has_commented
        context["no_jumbotron"] = True

        return context
        
def agree(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['obj_id']

    agree_count = 0

    if cat_id:
        cat = Link.objects.get(id=int(cat_id))
    if cat:
        if request.session.get('has_commented_' + cat_id, False):
            agree_count = cat.agree
        else:
            request.session['has_commented_' + cat_id] = True
            agree_count = cat.agree + 1
            cat.agree =  agree_count
            cat.save()
    return HttpResponse(agree_count)

def disagree(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['obj_id']

    disagree_count = 0

    if cat_id:
        cat = Link.objects.get(id=int(cat_id))
    if cat:
        if request.session.get('has_commented_' + cat_id, False):
            disagree_count = cat.disagree
        else:
            request.session['has_commented_' + cat_id] = True
            disagree_count = cat.disagree + 1
            cat.disagree =  disagree_count
            cat.save()
    return HttpResponse(disagree_count)

class LinkUpdateView(LoginRequiredMixin, UpdateView):
    model = Link
    form_class = LinkForm

class LinkDeleteView(LoginRequiredMixin, DeleteView):
    model = Link
    success_url = reverse_lazy("forum:forum")

class JSONFormMixin(object):
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict), content_type='application/json')
        response.status = 200 if valid_form else 500
        return response

class VoteFormBaseView(LoginRequiredMixin, FormView):
    form_class = VoteForm

    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict))
        response.status = 200 if valid_form else 500
        return response

    def form_valid(self, form):
        link = get_object_or_404(Link, pk=form.data["link"])
        user = self.request.user
        prev_votes = Vote.objects.filter(voter=user, link=link)
        has_voted = (len(prev_votes) > 0)

        ret = {"success": 1}
        if not has_voted:
            # add vote
            v = Vote.objects.create(voter=user, link=link)
            ret["voteobj"] = v.id
        else:
            # delete vote
            prev_votes[0].delete()
            ret["unvoted"] = 1
        return self.create_response(ret, True)

    def form_invalid(self, form):
        ret = {"success": 0, "form_errors": form.errors }
        return self.create_response(ret, False)

class VoteFormView(JSONFormMixin, VoteFormBaseView):
    pass

GTR/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .forms import UserForm
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

GTR/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
{% load humanize %}
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Quit or Stay{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="QuitorStay, Quit or Stay">
    <meta name="author" content="Musahshi">
    <meta name="copyright" content="Musashi">
    <link rel="author" href="project.musashi@gmail.com">
    <link rel="publisher" href="project.musashi@gmail.com">
    <meta property="og:title" content="QuitorStay" >
    <meta property="og:url" content="https://www.quitorstay.com/">
    <meta property="og:description" content="QuitorStay, Quit or Stay" >
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon"/>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
    {% endblock %}

  </head>

  <body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63595633-1', 'auto');
  ga('send', 'pageview');

</script>
    <nav role="navigation" class="navbar navbar-default navbar-static-top">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand"><b>Quit or Stay?</b></a>
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'forum:create' %}">New Post</a></li>
                <!--
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="#">Inbox</a></li>
                        <li><a href="#">Drafts</a></li>
                        <li><a href="#">Sent Items</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Trash</a></li>
                    </ul>
                </li> -->
            </ul>
            <form id="searchform" action="{% url 'forum:search' %}" method="get" accept-charset="utf-8" role="search" class="navbar-form navbar-left">
                <div class="form-group">
                    <input id="searchbox" name="q" type="text" placeholder="Search" class="form-control">
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                  <li><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
                  <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
                {% else %}
                  <li><a href="{% url 'account_login' %}">{% trans "Login" %}</a></li>
                  <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">

      {% if no_jumbotron %}
      {% else %}
      <div class="jumbotron">
      {% endif %}  
      
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
      
      {% if no_jumbotron %}
      {% else %}
      </div>
      {% endif %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}
      <footer class="footer">
        <div class="container">
          <div class="footer-middle">
          © 2015 QuitorStay inc. All rights reserved.<br>
          <a href="mailto:admin@quitorstay.com">Contact us<a>
          </div>
        </div>
      </footer>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
      <script src="{% static 'js/vote.js' %}"></script>
      <script src="{% static 'js/readmore.min.js' %}"></script>

      <script>
      $('article').readmore({
        collapsedHeight: 60,
        speed: 200,
        afterToggle: function(trigger, element, expanded) {
          if(! expanded) { // The "Close" link was clicked
            $('html, body').animate( { scrollTop: element.offset().top }, {duration: 100 } );
          }
        }
      });
      </script>

    {% endblock javascript %}
  </body>
</html>
 